
#pragma once

#include "a.h"

#include "../../fdc-hierarchy.h"

using namespace fdctest::a;

ROOT(Root)

TYPE(A0) EXTENDS(Root)
TYPE(A1) NEXTOF(A0)
TYPE(A2) NEXTOF(A1)
TYPE(A3) NEXTOF(A2)
TYPE(A4) NEXTOF(A3)

TYPE(B0) EXTENDS(A0)
TYPE(B1) NEXTOF(B0)
TYPE(B2) NEXTOF(B1)
TYPE(B3) NEXTOF(B2)
TYPE(B4) NEXTOF(B3)

TYPE(C0) EXTENDS(B0)
TYPE(C1) NEXTOF(C0)
TYPE(C2) NEXTOF(C1)
TYPE(C3) NEXTOF(C2)
TYPE(C4) NEXTOF(C3)

TYPE(D0) EXTENDS(C0)
TYPE(D1) NEXTOF(D0)
TYPE(D2) NEXTOF(D1)
TYPE(D3) NEXTOF(D2)
TYPE(D4) NEXTOF(D3)
